import {body,cors,error,json} from "../_shared/http.ts"; import {admin,bucket} from "../_shared/config.ts"; import {artifactPath,sanitize} from "../_shared/security.ts";
function databaseError(operation:string,failure:unknown){const code=String(failure&&typeof failure==="object"&&"code" in failure?(failure as {code?:unknown}).code??"":"");const reason=code==="42P01"||code==="PGRST205"?"schema_missing":code==="42703"||code==="PGRST204"?"schema_outdated":code==="42501"?"permission_denied":code.startsWith("PGRST")?"api_error":"database_error";return error(500,`${operation}_${reason}`,`${operation.replaceAll("_"," ")} failed`);}
Deno.serve(async(req)=>{ if(req.method==="OPTIONS") return new Response("ok",{headers:cors}); if(req.method!=="POST") return error(405,"method_not_allowed","POST required");
 try { const input=await body(req), key=String(input.idempotencyKey??""); if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(key)) return error(400,"invalid_idempotency_key","UUID required");
  const category=String(input.category??""); if(!["bug","usability","request","other"].includes(category)) return error(400,"invalid_category","unsupported category");
  const comment=sanitize(input.comment); if(!comment) return error(400,"invalid_comment","comment required");
  const artifacts=Array.isArray(input.artifacts)?input.artifacts as Record<string,unknown>[]:[]; if(!artifacts.length||artifacts.length>5) return error(400,"invalid_artifacts","1..5 artifacts required");const expectedMime:Record<string,string>={rawScreenshot:"image/png",rawLog:"application/x-ndjson",redactedScreenshot:"image/png",redactedLog:"application/x-ndjson",manifest:"application/json"},seen=new Set<string>();
  for(const a of artifacts) {const kind=String(a.kind);if(!expectedMime[kind]||seen.has(kind)||a.contentType!==expectedMime[kind]||!/^[a-f0-9]{64}$/.test(String(a.sha256)))return error(400,"invalid_artifact","kind, MIME, hash, or uniqueness invalid");seen.add(kind);if(!Number.isInteger(a.bytes)||Number(a.bytes)<1||Number(a.bytes)>10485760) return error(413,"artifact_too_large","artifact exceeds limit"); }
  const db=admin(), existing=await db.from("reports").select("id,status,expires_at,artifacts").eq("idempotency_key",key).maybeSingle();
  if(existing.error)return databaseError("report_lookup",existing.error);
  if(existing.data) {const uploads=[];if(existing.data.status==="uploading")for(const a of existing.data.artifacts as Record<string,unknown>[]){const kind=String(a.kind),path=artifactPath(existing.data.id,kind),signed=await db.storage.from(bucket).createSignedUploadUrl(path,{upsert:true});if(signed.error)return error(500,"upload_url_failed","upload URL creation failed");uploads.push({kind,path,localPath:path.slice(`reports/${existing.data.id}/`.length),url:signed.data.signedUrl,token:signed.data.token,contentType:a.contentType});}return json(200,{reportId:existing.data.id,status:existing.data.status,uploads,expiresAt:existing.data.expires_at,idempotent:true});}
  const clientKey=sanitize(req.headers.get("x-client-id")??req.headers.get("x-forwarded-for")??"unknown",200);const rate=await db.rpc("consume_report_rate_limit",{p_client_key:clientKey,p_limit:10});if(rate.error)return databaseError("rate_limit_check",rate.error);if(!rate.data)return error(429,"rate_limited","try again later");
  const app=input.app as Record<string,unknown>??{},appVersion=sanitize(app.version,80),consentedAt=String(input.consentedAt??"");if(!appVersion||Number.isNaN(Date.parse(consentedAt))||!input.environment||typeof input.environment!=="object"||Array.isArray(input.environment))return error(400,"invalid_metadata","app version, consent time, and environment required"); const inserted=await db.from("reports").insert({idempotency_key:key,reporter_name:sanitize(input.reporterName,80)||null,category,comment,expected:sanitize(input.expected)||null,app_version:appVersion,build_sha:sanitize(app.buildSha,64)||null,environment:input.environment,artifacts,consented_at:consentedAt}).select().single(); if(inserted.error)return databaseError("report_insert",inserted.error);
  const uploads=[]; for(const a of artifacts){const kind=String(a.kind),path=artifactPath(inserted.data.id,kind); const signed=await db.storage.from(bucket).createSignedUploadUrl(path,{upsert:true}); if(signed.error)return error(500,"upload_url_failed","upload URL creation failed"); uploads.push({kind,path,localPath:path.slice(`reports/${inserted.data.id}/`.length),url:signed.data.signedUrl,token:signed.data.token,contentType:a.contentType});}
  const paths:Record<string,string>={};for(const a of artifacts)paths[String(a.kind)]=artifactPath(inserted.data.id,String(a.kind));const updated=await db.from("reports").update({raw_screenshot_path:paths.rawScreenshot??null,raw_log_path:paths.rawLog??null,redacted_screenshot_path:paths.redactedScreenshot??null,redacted_log_path:paths.redactedLog??null}).eq("id",inserted.data.id);if(updated.error)return databaseError("report_path_update",updated.error);
  const event=await db.from("report_events").insert({report_id:inserted.data.id,event_type:"report_created",actor:"edge",details:{artifactCount:artifacts.length}});if(event.error)return databaseError("report_event",event.error);return json(201,{reportId:inserted.data.id,status:"uploading",uploads,expiresAt:inserted.data.expires_at});
 } catch(_e){return error(500,"create_failed","report creation failed");}});
