package dev.continuousimprovement.dispatcher.gateway;
import com.fasterxml.jackson.databind.JsonNode;import dev.continuousimprovement.core.JsonSupport;import dev.continuousimprovement.core.io.Hashing;import dev.continuousimprovement.dispatcher.ProcessRunner;
import java.net.*;import java.net.http.*;import java.nio.file.*;import java.time.Duration;import java.util.*;
public final class GhSupabaseControlPlane implements ControlPlane {
 private final ProcessRunner runner;private final Path repo;private final URI endpoint;private final String token;private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();
 public GhSupabaseControlPlane(ProcessRunner r,Path repo,URI endpoint,String token){runner=r;this.repo=repo;this.endpoint=endpoint;this.token=token;}
 public void recoverStale()throws Exception{call(Map.of("action","recoverStale"));}
 public Optional<WorkItem> nextReady()throws Exception{var out=gh("issue","list","--state","open","--label","agent-ready","--json","number,title,body,labels","--limit","10");JsonNode rows=JsonSupport.MAPPER.readTree(out);for(JsonNode row:rows){String agent=null;for(JsonNode l:row.path("labels")){String n=l.path("name").asText();if(n.equals("agent:codex"))agent="codex";if(n.equals("agent:claude"))agent="claude";}if(agent==null)continue;var match=java.util.regex.Pattern.compile("Report ID: `([0-9a-f-]{36})`").matcher(row.path("body").asText());if(match.find())return Optional.of(new WorkItem(UUID.fromString(match.group(1)),row.path("number").asLong(),row.path("title").asText(),row.path("body").asText(),agent));}return Optional.empty();}
 public Optional<RunClaim> claim(WorkItem i)throws Exception{JsonNode n=call(Map.of("action","claim","reportId",i.reportId(),"issueNumber",i.issueNumber(),"agent",i.agent()));if(!n.path("claimed").asBoolean())return Optional.empty();gh("issue","edit",Long.toString(i.issueNumber()),"--remove-label","agent-ready","--add-label","agent-running");return Optional.of(new RunClaim(UUID.fromString(n.path("runId").asText()),i));}
 public Path fetchRedacted(RunClaim c,Path target)throws Exception{Files.createDirectories(target);JsonNode response=call(Map.of("action","artifacts","reportId",c.item().reportId()));for(JsonNode a:response.path("artifacts")){String kind=a.path("kind").asText();String name=switch(kind){case"redactedScreenshot"->"screenshot.png";case"redactedLog"->"logs.jsonl";case"manifest"->"manifest.json";default->throw new IllegalStateException("raw or unknown artifact returned");};Path file=target.resolve(name);var request=HttpRequest.newBuilder(URI.create(a.path("url").asText())).GET().timeout(Duration.ofSeconds(30)).build();var got=http.send(request,HttpResponse.BodyHandlers.ofFile(file));if(got.statusCode()/100!=2)throw new IllegalStateException("artifact download failed");if(!Hashing.sha256(Files.readAllBytes(file)).equals(a.path("sha256").asText()))throw new IllegalStateException("artifact hash mismatch");}return target;}
 public void running(RunClaim c)throws Exception{status(c,"running",null,null);}
 public void failed(RunClaim c,String code,String detail)throws Exception{status(c,"failed",code,detail);labels(c,"agent-running","agent-failed");}
 public void needsInfo(RunClaim c,String detail)throws Exception{status(c,"needs_info",null,detail);labels(c,"agent-running","needs-info");}
 public String openDraftPr(RunClaim c,String branch,String body)throws Exception{return gh("pr","create","--draft","--head",branch,"--title","Agent fix for #"+c.item().issueNumber(),"--body",body).trim();}
 public void prOpened(RunClaim c,String branch,String url)throws Exception{status(c,"completed",null,url);labels(c,"agent-running","pr-opened");}
 private void labels(RunClaim c,String remove,String add)throws Exception{gh("issue","edit",Long.toString(c.item().issueNumber()),"--remove-label",remove,"--add-label",add);}
 private void status(RunClaim c,String status,String code,String detail)throws Exception{Map<String,Object> m=new LinkedHashMap<>();m.put("action","status");m.put("runId",c.runId());m.put("reportId",c.item().reportId());m.put("status",status);if(code!=null)m.put("failureCode",code);if(detail!=null)m.put("detail",detail);call(m);}
 private JsonNode call(Object payload)throws Exception{var req=HttpRequest.newBuilder(endpoint).header("authorization","Bearer "+token).header("content-type","application/json").POST(HttpRequest.BodyPublishers.ofByteArray(JsonSupport.MAPPER.writeValueAsBytes(payload))).timeout(Duration.ofSeconds(30)).build();var response=http.send(req,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2)throw new IllegalStateException("control plane HTTP "+response.statusCode());return JsonSupport.MAPPER.readTree(response.body());}
 private String gh(String...args)throws Exception{var cmd=new ArrayList<String>();cmd.add("gh");cmd.addAll(List.of(args));var x=runner.runControl(cmd,repo,Duration.ofMinutes(2),Map.of());if(!x.succeeded())throw new IllegalStateException("gh failed: "+x.output());return x.output();}
}
