package dev.continuousimprovement.app.report;
import com.sun.net.httpserver.*;import dev.continuousimprovement.core.model.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.io.IOException;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Instant;import java.util.UUID;import java.util.concurrent.atomic.AtomicInteger;import static org.junit.jupiter.api.Assertions.*;
class RemoteReportClientTest {
 @TempDir Path temp;
 @Test void sendsContractPayloadUploadsAndFinalizes()throws Exception{UUID id=UUID.randomUUID();Path bundle=new LocalReportBundleWriter().write(temp,new ReportBundleRequest(id,"user",ReportCategory.BUG,"broken","fixed",Instant.now(),"1","abc",new EnvironmentInfo("Ubuntu","24.04","amd64","25","25","ja","main","x11"),bytes("raw-image"),bytes("safe-image"),bytes("raw-log"),bytes("safe-log"),true));AtomicInteger uploads=new AtomicInteger();StringBuilder createBody=new StringBuilder();HttpServer server=HttpServer.create(new InetSocketAddress(InetAddress.getLoopbackAddress(),0),0);String base="http://127.0.0.1:"+server.getAddress().getPort();
  server.createContext("/functions/v1/create-report",x->{createBody.append(new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));reply(x,200,"{\"reportId\":\"id\",\"status\":\"uploading\",\"expiresAt\":\"2099-01-01T00:00:00Z\",\"idempotent\":false,\"uploads\":[{\"kind\":\"rawScreenshot\",\"path\":\"reports/id/raw/screenshot.png\",\"token\":\"unused\",\"localPath\":\"raw/screenshot.png\",\"url\":\""+base+"/upload\",\"contentType\":\"image/png\"},{\"localPath\":\"raw/logs.jsonl\",\"url\":\""+base+"/upload\",\"contentType\":\"application/x-ndjson\"},{\"localPath\":\"redacted/screenshot.png\",\"url\":\""+base+"/upload\",\"contentType\":\"image/png\"},{\"localPath\":\"redacted/logs.jsonl\",\"url\":\""+base+"/upload\",\"contentType\":\"application/x-ndjson\"},{\"localPath\":\"manifest.json\",\"url\":\""+base+"/upload\",\"contentType\":\"application/json\"}]}");});server.createContext("/upload",x->{x.getRequestBody().readAllBytes();uploads.incrementAndGet();reply(x,200,"{}");});server.createContext("/functions/v1/finalize-report",x->{x.getRequestBody().readAllBytes();reply(x,200,"{\"reportId\":\"id\",\"status\":\"issue_created\",\"issueUrl\":\"https://example.invalid/issues/1\",\"idempotent\":false}");});server.start();try(var client=new RemoteReportClient(URI.create(base),"publishable")){var result=client.submit(bundle);assertEquals("issue_created",result.status());assertEquals(5,uploads.get());assertTrue(createBody.toString().contains("\"category\":\"bug\""));assertTrue(createBody.toString().contains("\"app\":"));assertFalse(createBody.toString().contains("RAW_SCREENSHOT"));}finally{server.stop(0);}}
 @Test void reportsFinalServerErrorAfterRetries()throws Exception{Path bundle=bundle();AtomicInteger requests=new AtomicInteger();HttpServer server=HttpServer.create(new InetSocketAddress(InetAddress.getLoopbackAddress(),0),0);String base="http://127.0.0.1:"+server.getAddress().getPort();server.createContext("/functions/v1/create-report",x->{requests.incrementAndGet();x.getRequestBody().readAllBytes();reply(x,500,"{\"error\":{\"code\":\"report_lookup_failed\",\"message\":\"safe\"}}");});server.start();try(var client=new RemoteReportClient(URI.create(base),"publishable")){IOException error=assertThrows(IOException.class,()->client.submit(bundle));assertEquals("create-report failed with HTTP 500 (report_lookup_failed)",error.getMessage());assertEquals(3,requests.get());}finally{server.stop(0);}}
 @Test void rejectsMissingUploadPath()throws Exception{Path bundle=bundle();HttpServer server=HttpServer.create(new InetSocketAddress(InetAddress.getLoopbackAddress(),0),0);String base="http://127.0.0.1:"+server.getAddress().getPort();server.createContext("/functions/v1/create-report",x->{x.getRequestBody().readAllBytes();reply(x,200,"{\"reportId\":\"id\",\"uploads\":[{\"url\":\""+base+"/upload\",\"contentType\":\"image/png\"}]}");});server.start();try(var client=new RemoteReportClient(URI.create(base),"publishable")){IOException error=assertThrows(IOException.class,()->client.submit(bundle));assertEquals("create-report returned an invalid upload path",error.getMessage());}finally{server.stop(0);}}
 private Path bundle()throws IOException{return new LocalReportBundleWriter().write(temp,new ReportBundleRequest(UUID.randomUUID(),"user",ReportCategory.BUG,"broken","fixed",Instant.now(),"1","abc",new EnvironmentInfo("Ubuntu","24.04","amd64","25","25","ja","main","x11"),bytes("raw-image"),bytes("safe-image"),bytes("raw-log"),bytes("safe-log"),true));}
 private static byte[] bytes(String s){return s.getBytes(StandardCharsets.UTF_8);}private static void reply(HttpExchange x,int status,String value)throws java.io.IOException{byte[] data=value.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().add("content-type","application/json");x.sendResponseHeaders(status,data.length);x.getResponseBody().write(data);x.close();}
}
