package dev.continuousimprovement.dispatcher.agent;
import dev.continuousimprovement.core.model.AgentResult;import dev.continuousimprovement.dispatcher.ProcessRunner;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.time.Duration;import static org.junit.jupiter.api.Assertions.*;
class AgentAdapterTest {
 @TempDir Path temp;
 private static final String RESULT="{\"outcome\":\"changed\",\"summary\":\"ok\",\"tests\":[],\"filesChanged\":[\"x\"],\"risks\":[],\"questions\":[]}";
 @Test void codexReadsOutputLastMessageFile()throws Exception{Path bin=script("codex-fake","#!/bin/sh\nwhile [ $# -gt 0 ]; do if [ \"$1\" = \"--output-last-message\" ]; then shift; printf '%s' '"+RESULT+"' > \"$1\"; exit 0; fi; shift; done\nexit 2\n");var x=new CodexAdapter(new ProcessRunner(),bin.toString()).execute(temp,temp,"prompt",temp.resolve("result.json"),Duration.ofSeconds(5));assertEquals(AgentResult.Outcome.CHANGED,x.result().outcome());}
 @Test void claudeReadsJsonEnvelope()throws Exception{String escaped=RESULT.replace("\\","\\\\").replace("\"","\\\"");Path bin=script("claude-fake","#!/bin/sh\nprintf '%s' '{\"result\":\""+escaped+"\"}'\n");var x=new ClaudeAdapter(new ProcessRunner(),bin.toString()).execute(temp,temp,"prompt",temp.resolve("result.json"),Duration.ofSeconds(5));assertEquals(AgentResult.Outcome.CHANGED,x.result().outcome());}
 @Test void singleTestObjectIsAcceptedAsArray()throws Exception{String lone="{\"outcome\":\"changed\",\"summary\":\"ok\",\"tests\":{\"command\":\"./gradlew test\",\"result\":\"passed\"},\"filesChanged\":[\"x\"],\"risks\":[],\"questions\":[],\"extra\":\"ignored\"}";Path result=temp.resolve("result.json");Path bin=script("codex-lone","#!/bin/sh\nexit 0\n");Files.writeString(result,lone);var x=new CodexAdapter(new ProcessRunner(),bin.toString()).execute(temp,temp,"prompt",result,Duration.ofSeconds(5));assertEquals(1,x.result().tests().size());assertEquals("./gradlew test",x.result().tests().get(0).command());}
 @Test void malformedResultRaisesFormatExceptionInsteadOfCrashing()throws Exception{Path result=temp.resolve("result.json");Path bin=script("codex-bad","#!/bin/sh\nexit 0\n");Files.writeString(result,"{\"outcome\":\"changed\",\"summary\":\"ok\",\"tests\":[\"./gradlew test\"],\"filesChanged\":[],\"risks\":[],\"questions\":[]}");var adapter=new CodexAdapter(new ProcessRunner(),bin.toString());var e=assertThrows(AgentResultFormatException.class,()->adapter.execute(temp,temp,"prompt",result,Duration.ofSeconds(5)));assertTrue(e.getMessage().startsWith("agent result JSON does not match the required schema"));}
 @Test void promptCarriesTheResultContract()throws Exception{Path seen=temp.resolve("prompt.txt");Path bin=script("codex-echo","#!/bin/sh\nprintf '%s' \"$*\" > \""+seen+"\"\nexit 3\n");new CodexAdapter(new ProcessRunner(),bin.toString()).execute(temp,temp,"prompt",temp.resolve("result.json"),Duration.ofSeconds(5));String prompt=Files.readString(seen);assertTrue(prompt.contains("\"tests\":[{\"command\":\"./gradlew test\",\"result\":\"passed|failed|not_run\"}]"),prompt);assertTrue(prompt.contains("always JSON arrays"),prompt);}
 @Test void promptNamesTheEvidenceFiles()throws Exception{Path evidence=Files.createDirectory(temp.resolve("evidence"));Files.writeString(evidence.resolve("manifest.json"),"{}");Files.writeString(evidence.resolve("screenshot.png"),"x");Files.createDirectory(evidence.resolve("nested"));Path seen=temp.resolve("prompt.txt");Path bin=script("codex-evidence","#!/bin/sh\nprintf '%s' \"$*\" > \""+seen+"\"\nexit 3\n");new CodexAdapter(new ProcessRunner(),bin.toString()).execute(temp,evidence,"prompt",temp.resolve("result.json"),Duration.ofSeconds(5));String prompt=Files.readString(seen);assertTrue(prompt.contains("manifest.json, screenshot.png"),prompt);assertFalse(prompt.contains("nested"),prompt);}
 @Test void promptSaysSoWhenNoEvidenceWasFetched()throws Exception{Path evidence=Files.createDirectory(temp.resolve("evidence"));Path seen=temp.resolve("prompt.txt");Path bin=script("codex-noevidence","#!/bin/sh\nprintf '%s' \"$*\" > \""+seen+"\"\nexit 3\n");new CodexAdapter(new ProcessRunner(),bin.toString()).execute(temp,evidence,"prompt",temp.resolve("result.json"),Duration.ofSeconds(5));assertTrue(Files.readString(seen).contains("no evidence files"),Files.readString(seen));}
 private Path script(String name,String content)throws Exception{Path p=temp.resolve(name);Files.writeString(p,content);assertTrue(p.toFile().setExecutable(true));return p;}
}
