package dev.continuousimprovement.dispatcher;
import dev.continuousimprovement.core.model.AgentResult;import dev.continuousimprovement.dispatcher.agent.*;import dev.continuousimprovement.dispatcher.gateway.*;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import org.junit.jupiter.params.ParameterizedTest;import org.junit.jupiter.params.provider.ValueSource;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class DispatcherPilotTest {
 @TempDir Path temp;
 @ParameterizedTest @ValueSource(strings={"codex","claude","codex","claude","codex"})
 void fiveFixtureReportsReachDraftPr(String agent)throws Exception{Path seed=seedRepository();
  var control=new FixtureControl(agent);AgentAdapter fake=new AgentAdapter(){public String name(){return agent;}public AgentExecution execute(Path worktree,Path evidence,String prompt,Path result,java.time.Duration timeout)throws Exception{Files.writeString(worktree.resolve("README.md"),"improved by "+agent+"\n");var r=new AgentResult(AgentResult.Outcome.CHANGED,"fixture improvement",List.of(new AgentResult.TestResult("./gradlew test","passed")),List.of("README.md"),List.of(),List.of());return new AgentExecution(0,false,"ok",r);}};var runner=new ProcessRunner();var outcome=new Dispatcher(control,List.of(fake),runner,new VerificationGate(runner,100),seed,temp.resolve("runs")).runOnce();assertEquals(Dispatcher.Outcome.PR_OPENED,outcome);assertEquals(1,control.prs);assertEquals("pr-opened",control.status);}
 @Test void malformedAgentResultFailsTheRunInsteadOfTheProcess()throws Exception{Path seed=seedRepository();var control=new FixtureControl("claude");
  AgentAdapter broken=new AgentAdapter(){public String name(){return "claude";}public AgentExecution execute(Path worktree,Path evidence,String prompt,Path result,java.time.Duration timeout)throws Exception{throw new AgentResultFormatException("agent result JSON does not match the required schema: tests is not an array",0,"agent output");}};
  var runner=new ProcessRunner();var outcome=new Dispatcher(control,List.of(broken),runner,new VerificationGate(runner,100),seed,temp.resolve("runs")).runOnce();
  assertEquals(Dispatcher.Outcome.FAILED,outcome);assertEquals("failed",control.status);assertEquals("invalid_agent_result",control.failureCode);assertEquals(0,control.prs);}
 @Test void readOnlyEvidenceIsStillDeletedWhenTheRunEnds()throws Exception{Path seed=seedRepository();var control=new FixtureControl("claude");Path scratch=temp.resolve("runs");
  AgentAdapter fake=new AgentAdapter(){public String name(){return "claude";}public AgentExecution execute(Path worktree,Path evidence,String prompt,Path result,java.time.Duration timeout)throws Exception{Files.writeString(worktree.resolve("README.md"),"improved\n");var r=new AgentResult(AgentResult.Outcome.CHANGED,"fixture improvement",List.of(new AgentResult.TestResult("./gradlew test","passed")),List.of("README.md"),List.of(),List.of());return new AgentExecution(0,false,"ok",r);}};
  var runner=new ProcessRunner();assertEquals(Dispatcher.Outcome.PR_OPENED,new Dispatcher(control,List.of(fake),runner,new VerificationGate(runner,100),seed,scratch).runOnce());
  assertFalse(Files.exists(scratch.resolve(control.run.toString())),"redacted evidence survived cleanup");}
 private Path seedRepository()throws Exception{Path remote=temp.resolve("remote.git"),seed=temp.resolve("seed");command(temp,"git","init","--bare","-q",remote.toString());Files.createDirectories(seed);command(seed,"git","init","-q");command(seed,"git","config","user.email","test@example.invalid");command(seed,"git","config","user.name","Test");Files.writeString(seed.resolve("README.md"),"before\n");Files.writeString(seed.resolve("gradlew"),"#!/bin/sh\nexit 0\n");seed.resolve("gradlew").toFile().setExecutable(true);command(seed,"git","add",".");command(seed,"git","commit","-qm","base");command(seed,"git","branch","-M","main");command(seed,"git","remote","add","origin",remote.toString());command(seed,"git","push","-qu","origin","main");command(remote,"git","symbolic-ref","HEAD","refs/heads/main");command(seed,"git","fetch","-q","origin");return seed;}
 private static void command(Path dir,String...args)throws Exception{var p=new ProcessBuilder(args).directory(dir.toFile()).start();assertEquals(0,p.waitFor(),new String(p.getErrorStream().readAllBytes()));}
 private final class FixtureControl implements ControlPlane {final WorkItem item;final UUID run=UUID.randomUUID();int prs;String status;String failureCode;FixtureControl(String agent){item=new WorkItem(UUID.randomUUID(),42,"fixture","Report ID: fixture",agent);}public Optional<WorkItem>nextReady(){return Optional.of(item);}public Optional<RunClaim>claim(WorkItem i){return Optional.of(new RunClaim(run,i));}public Path fetchRedacted(RunClaim c,Path target)throws Exception{Files.createDirectories(target);Files.writeString(target.resolve("logs.jsonl"),"{}\n");return target;}public void running(RunClaim c){status="running";}public void failed(RunClaim c,String x,String y){status="failed";failureCode=x;}public void needsInfo(RunClaim c,String d){status="needs-info";}public String openDraftPr(RunClaim c,String b,String body){prs++;return "https://example.invalid/pr/1";}public void prOpened(RunClaim c,String b,String u){status="pr-opened";}}
}
